# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
aliases:
  - &container_python
    docker:
      - image: cimg/python:3.9.10  # primary container for the build job

  - &run_task_install_dependencies
    run:
      name: install tox dependencies
      command: |
        sudo apt-get -qq update
        sudo apt install -y build-essential libssl-dev libpython2-dev python3-pip
        sudo pip3 install tox
      name: Install the latest version of Poetry
      command: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_UNINSTALL=1 python -
        curl -sSL https://install.python-poetry.org | python3 -
      name: use python 3.9.10
      command: |
        poetry env use 3.9.10
      name: Install dependencies # install all dependencies
      command: |
        poetry install

jobs:
  testing:
    <<: *container_python
    steps:
      - checkout
      - *run_task_install_dependencies
      - run:
          name: run tests
          command: |
            tox -e test
      - store_test_results:
          path: .tox/test/tmp/reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - testing
